# Generated by Django 3.1.4 on 2020-12-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20201205_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_files',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
    ]
