# Generated by Django 3.1.4 on 2020-12-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_files',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
    ]
